# -*- coding: utf-8 -*-
"""new_svm.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MRcWpJjsafgC_CXDeET7VGLSyuFXJsqb
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

data = pd.read_csv('Life.csv')

df = pd.DataFrame(data)

df.head(3)

df.isnull().sum()

df.fillna(value = df.mean(), inplace = True)

df.isnull().sum()

plt.figure(figsize = (14, 10))
sns.heatmap(df.corr(), annot = True)

df = df.drop(['Country','Status','Year','infant deaths', 'Hepatitis B','Measles ','under-five deaths ', 'Total expenditure', 'Population'], axis = 1)

df.head(1)

x = df.iloc[:,:-1].values
y = df.iloc[:,-1].values
reshape_y = np.reshape(y,(2938,1))
print(y)

from sklearn.preprocessing import MinMaxScaler
min_max_scaler = MinMaxScaler()
x = min_max_scaler.fit_transform(x)

x

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x,reshape_y,test_size=0.33)

# For Support Vector Machine
from sklearn.svm import SVR
regressor = SVR(kernel = 'rbf')
regressor.fit(x, reshape_y)

SVR()

regressor.score(X_train,y_train)

# For Decision Tree
from sklearn.tree import DecisionTreeRegressor
regressortree = DecisionTreeRegressor(random_state = 0)
regressortree.fit(x, y)

DecisionTreeRegressor()

regressortree.score(X_train,y_train)

y_pred = regressortree.predict(X_test)

from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

lw = 2
plt.scatter(x, y_pred, color='darkorange', label='data')
plt.hold('on')
plt.plot(X, y_predict, color='navy', lw=lw, label='RBF model')
plt.xlabel('data')
plt.ylabel('target')
plt.title('Support Vector Regression')
plt.legend()
plt.show()

x

reshape_y

